# By default, SwiftLint uses a set of sensible default rules you can adjust:
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - CCocoMediaSDK

included: # paths to include during linting. `--path` is ignored if present.
  - CocoMediaSDK

disabled_rules: # rule identifiers turned on by default to exclude from running
  - convenience_type
  - line_length
  - trailing_whitespace
  - type_name
  - identifier_name
  - vertical_whitespace
  - trailing_newline
  - opening_brace
  - large_tuple
  - file_length
  - comma
  - colon
  - private_over_fileprivate
  - force_cast
  - force_try
  - function_parameter_count
  - statement_position
  - legacy_hashing
  - todo
  - operator_whitespace
  - type_body_length
  - function_body_length
  - cyclomatic_complexity

opt_in_rules: # some rules are turned off by default, so you need to opt-in
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - first_where
  - closure_spacing
  - unneeded_parentheses_in_closure_argument
  - redundant_nil_coalescing
  - pattern_matching_keywords
  - explicit_init
  - contains_over_first_not_nil

reporter: "xcode"
